# Generated by Django 4.2.1 on 2023-05-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('default', 'default'), ('IMAX', 'IMAX')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('budget', models.FloatField()),
                ('poster', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('trailerUrl', models.CharField(max_length=50)),
                ('genre', models.ManyToManyField(to='cinema.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('3D', '3D'), ('2D', '2D')], max_length=30)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='cinema.seattype'),
        ),
    ]
