# Generated by Django 4.2.1 on 2023-05-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.seat'),
        ),
        migrations.AlterField(
            model_name='sessionseat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_seats', to='cinema.session'),
        ),
    ]
