# Generated by Django 4.2.1 on 2023-05-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_ticket_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.profile'),
            preserve_default=False,
        ),
    ]
