# Generated by Django 4.2.1 on 2023-05-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_sessionseat_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session_seat',
        ),
    ]
