# Generated by Django 4.2.1 on 2023-05-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_sessionseat_session_seat_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionseat',
            old_name='session_seat',
            new_name='user',
        ),
    ]
