# Generated by Django 4.2.1 on 2023-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_sessionseat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='startDate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie', to='cinema.genre'),
        ),
        migrations.AlterField(
            model_name='session',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
