# Generated by Django 4.2.1 on 2023-05-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_session_startdate_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='startDate',
        ),
    ]
