# Generated by Django 4.2.1 on 2023-09-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_alter_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
