# Generated by Django 4.2.1 on 2023-11-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_add_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=1000000)),
                ('is_rotation_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
