# Generated by Django 4.2.1 on 2023-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_remove_rotationsettings_is_rotation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionseat',
            name='final_cost',
            field=models.FloatField(default=0),
        ),
    ]
